version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - AUTH_API=http://auth-microservice:5001
      - COURSE_API=http://course-microservice:5002
      - ENROLLMENT_API=http://enrollment-microservice:5003
      - PAYMENT_API=http://payment-microservice:5004
    depends_on:
      - auth-microservice
      - course-microservice
    networks:
      - app-network

  auth-microservice:
    build:
      context: ./auth-microservice
    expose:
      - "5001"
    networks:
      - app-network

  course-microservice:
    build:
      context: ./course-microservice
    expose:
      - "5002"
    networks:
      - app-network

  enrollment-microservice:
    build:
      context: ./enrollment-microservice
    expose:
      - "5003"
    networks:
      - app-network

  payment-microservice:
    build:
      context: ./payment-microservice
    expose:
      - "5004"
    networks:
      - app-network
